// Datos REALES — Fuente: CMF (Comisión para el Mercado Financiero)
// Rentabilidades calculadas con valor cuota oficial CMF
// rent30: variación último mes (marzo 2026)
// rent90: variación 3 meses (dic 2025 → mar 2026)
// rent180: variación 6 meses (sep 2025 → mar 2026)
// rent360: variación 12 meses (mar 2025 → mar 2026)
// 299 fondos de 10 instituciones
const FUNDS_DATA = [
  {
    "name": "Banchile Depósito XXI",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 1.09,
    "rent90": 2.59,
    "rent180": 3.68,
    "rent360": 5.91,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Disponible",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.27,
    "rent90": 0.87,
    "rent180": 1.75,
    "rent360": 3.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Ahorro Nominal",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.21,
    "rent90": 0.91,
    "rent180": 0,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Global Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -4.34,
    "rent90": -3.48,
    "rent180": 1.31,
    "rent360": 33.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Emerging",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -3.18,
    "rent90": 5.95,
    "rent180": 3.55,
    "rent360": 29.13,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Blackrock ESG",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.5,
    "rent90": -3.09,
    "rent180": -4.94,
    "rent360": 16.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Horizonte",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.13,
    "rent90": 2.46,
    "rent180": 3.97,
    "rent360": 6.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Estrategico",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.99,
    "rent90": 2.35,
    "rent180": 3.41,
    "rent360": 5.88,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Capital Financiero",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.34,
    "rent90": 1.14,
    "rent180": 2.31,
    "rent360": 4.77,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Utilidades",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.47,
    "rent90": 2.28,
    "rent180": 2.61,
    "rent360": 4.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Renta Corto Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.66,
    "rent90": 1.51,
    "rent180": 2.34,
    "rent360": 4.52,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Deuda Soberana",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.74,
    "rent90": 1.7,
    "rent180": 3.65,
    "rent360": 4.2,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Corporate Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.25,
    "rent90": 0.84,
    "rent180": 1.71,
    "rent360": 3.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Capital Empresarial",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.24,
    "rent90": 0.82,
    "rent180": 1.66,
    "rent360": 3.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Deuda Dólar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.14,
    "rent90": 0.39,
    "rent180": 1.15,
    "rent360": 3.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Deuda Global",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0,
    "rent90": 0,
    "rent180": 0,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Emerging Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0,
    "rent90": 0,
    "rent180": 0,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile U.s Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0,
    "rent90": 0,
    "rent180": 0,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Moderado",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.66,
    "rent90": 0.98,
    "rent180": 2.35,
    "rent360": 15.4,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Moderado Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.42,
    "rent90": 1.16,
    "rent180": 2.4,
    "rent360": 15.29,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Conservador",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.64,
    "rent90": 1.88,
    "rent180": 3.2,
    "rent360": 9.69,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Retorno Mediano Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.06,
    "rent90": 2.35,
    "rent180": 3.26,
    "rent360": 5.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Ahorro Corto Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.73,
    "rent90": 1.47,
    "rent180": 2.18,
    "rent360": 4.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Conservador Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0,
    "rent90": 0,
    "rent180": 0,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Latam Accionario",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.5,
    "rent90": 17.76,
    "rent180": 20.21,
    "rent360": 50.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Selección Acciones Chilenas",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.62,
    "rent90": 1.39,
    "rent180": 20.66,
    "rent360": 48.97,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Dividendos Acciones Chilenas",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.09,
    "rent90": 2.95,
    "rent180": 18.51,
    "rent360": 40.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Renta Variable Nacional",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.63,
    "rent90": 1.09,
    "rent180": 17.07,
    "rent360": 39.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Global Accionario",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -2.05,
    "rent90": -1.32,
    "rent180": -2.69,
    "rent360": 24.64,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Inversión USA",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -1.98,
    "rent90": -3.98,
    "rent180": -5.86,
    "rent360": 24.29,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Asiatico Emergente",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -4.83,
    "rent90": 2.86,
    "rent180": -0.5,
    "rent360": 24.21,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Agresivo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -1.55,
    "rent90": 0.68,
    "rent180": 2.15,
    "rent360": 22.96,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Agresivo Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -1.74,
    "rent90": 0.44,
    "rent180": 1.87,
    "rent360": 22.52,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Europa Desarrollada",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -1.87,
    "rent90": 1.42,
    "rent180": 2.47,
    "rent360": 20.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Ahorro Corto Plazo",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 1.4,
    "rent90": 2.19,
    "rent180": 2.55,
    "rent360": 4.51,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Xii",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.28,
    "rent90": 0.96,
    "rent180": 1.96,
    "rent360": 4.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Xi",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.28,
    "rent90": 0.91,
    "rent180": 1.9,
    "rent360": 4.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Xiii",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent90": 1.07,
    "rent180": 1.67,
    "rent360": 3.82,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Asg",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.24,
    "rent90": 0.81,
    "rent180": 1.62,
    "rent360": 3.31,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Dolar Disponible",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.22,
    "rent90": 0.76,
    "rent180": 1.54,
    "rent360": 3.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Deuda Brasil",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.43,
    "rent90": 8.52,
    "rent180": 8.36,
    "rent360": 24.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Renta Futura",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.93,
    "rent90": 2.3,
    "rent180": 3.3,
    "rent360": 5.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Chile Ecologico",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.65,
    "rent90": 1.73,
    "rent180": 3.14,
    "rent360": 5.28,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Estructurado Renta UF",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.98,
    "rent90": 2.8,
    "rent180": 2.97,
    "rent360": 5.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Compromiso Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.07,
    "rent90": 2.35,
    "rent180": 3.09,
    "rent360": 5.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Mi Futuro Accesible",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent90": 1.35,
    "rent180": 2.46,
    "rent360": 4.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Mas Renta Bicentenario",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.25,
    "rent90": 1.11,
    "rent180": 2.38,
    "rent360": 4.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Proteccion Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.6,
    "rent90": 1.36,
    "rent180": 2.09,
    "rent360": 4.16,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Solvente Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.27,
    "rent90": 0.91,
    "rent180": 1.85,
    "rent360": 3.82,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Deuda Largo Plazo",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.61,
    "rent90": 1.27,
    "rent180": 3.4,
    "rent360": 3.68,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Conveniencia Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.25,
    "rent90": 0.83,
    "rent180": 1.7,
    "rent360": 3.51,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Perfil  A",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.02,
    "rent90": 0.53,
    "rent180": 1.95,
    "rent360": 17.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Perfil C",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.2,
    "rent90": 1.43,
    "rent180": 3.03,
    "rent360": 12.96,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Perfil  E",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.63,
    "rent90": 1.77,
    "rent180": 3.26,
    "rent360": 7.07,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Mi Futuro Moderado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.58,
    "rent90": 1.72,
    "rent180": 3.18,
    "rent360": 6.85,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Mi Futuro Conservador",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.77,
    "rent90": 1.94,
    "rent180": 3.09,
    "rent360": 5.63,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Chile Sostenible Conservador",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.36,
    "rent90": 1.23,
    "rent180": 2.55,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Acciones Nacionales",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.86,
    "rent90": 0.58,
    "rent180": 16.1,
    "rent360": 36.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Acciones Desarrolladas",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.71,
    "rent90": -1.33,
    "rent180": -2.61,
    "rent360": 17.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Mercados Emergentes",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -0.65,
    "rent90": 4.48,
    "rent180": 2.37,
    "rent360": 14.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Competitivo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent90": 1.21,
    "rent180": 2.43,
    "rent360": 4.96,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Ahorro Digital",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.3,
    "rent90": 1.04,
    "rent180": 2.12,
    "rent360": 4.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deposito Efectivo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent90": 0.96,
    "rent180": 1.94,
    "rent360": 3.99,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Dolar Cash",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.24,
    "rent90": 0.83,
    "rent180": 1.7,
    "rent360": 3.48,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI America Latina",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.99,
    "rent90": 10.19,
    "rent180": 12.79,
    "rent360": 26.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia UF > 5 Años",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.17,
    "rent90": 2.3,
    "rent180": 3.81,
    "rent360": 6.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Latam HY",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.24,
    "rent90": -1.11,
    "rent180": -0.22,
    "rent360": 5.82,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Global",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.72,
    "rent90": -1.35,
    "rent180": 0.17,
    "rent360": 5.81,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Corporativa Estratégica",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1,
    "rent90": 2.25,
    "rent180": 3.33,
    "rent360": 5.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estructurado UF Vii",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.83,
    "rent90": 2.73,
    "rent180": 3.1,
    "rent360": 5.38,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estructurado UF Vi",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.77,
    "rent90": 2.67,
    "rent180": 3.05,
    "rent360": 5.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia UF Hasta 5 Años",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.98,
    "rent90": 2.18,
    "rent180": 3.12,
    "rent360": 5.03,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI  Estrategia UF Hasta 3 Años",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.15,
    "rent90": 2.31,
    "rent180": 2.93,
    "rent360": 4.7,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia UF Hasta 1 Año",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.48,
    "rent90": 2.26,
    "rent180": 2.55,
    "rent360": 4.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia Pesos Hasta 1 Año",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.67,
    "rent90": 1.49,
    "rent180": 2.21,
    "rent360": 4.35,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Corto Plazo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.31,
    "rent90": 1.03,
    "rent180": 2.08,
    "rent360": 4.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Latam IG",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.58,
    "rent90": -1.82,
    "rent180": -0.81,
    "rent360": 4.19,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia Pesos Mayor A 1 Año",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.22,
    "rent90": 1.03,
    "rent180": 2.29,
    "rent360": 4.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.27,
    "rent90": 0.89,
    "rent180": 1.83,
    "rent360": 3.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Rendimiento",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.23,
    "rent90": 0.77,
    "rent180": 1.56,
    "rent360": 3.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Retorno Dólar IG",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.65,
    "rent90": 0.08,
    "rent180": 0.75,
    "rent360": 3.1,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Global Sostenible",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.95,
    "rent90": -1.16,
    "rent180": -0.63,
    "rent360": 1.2,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Mediano Plazo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.12,
    "rent90": 2.03,
    "rent180": 2.69,
    "rent360": -20.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinamica Chile",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 2.82,
    "rent90": 2.11,
    "rent180": 11.09,
    "rent360": 22.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Activa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.7,
    "rent90": 0.51,
    "rent180": 2.79,
    "rent360": 22.28,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinamica Activa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.77,
    "rent90": -0.45,
    "rent180": 1.41,
    "rent360": 19.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Balanceada",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.8,
    "rent90": 1.35,
    "rent180": 3.5,
    "rent360": 15.41,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinámica Balanceada",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.4,
    "rent90": 0.98,
    "rent180": 2.63,
    "rent360": 13.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dolar Balanceada",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -3.67,
    "rent90": -3.92,
    "rent180": -1.17,
    "rent360": 13.53,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach Moderado",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.21,
    "rent90": -0.21,
    "rent180": -0.64,
    "rent360": 12.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinámica Conservadora",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.51,
    "rent90": 2.03,
    "rent180": 3.5,
    "rent360": 8.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dólar Conservadora",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -2.79,
    "rent90": -2.05,
    "rent180": 0.12,
    "rent360": 8.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Conservadora",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.72,
    "rent90": 2.26,
    "rent180": 3.47,
    "rent360": 8.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach Conservador",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.07,
    "rent90": 1.01,
    "rent180": 1.24,
    "rent360": 8.01,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Ahorro",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.02,
    "rent90": 2.33,
    "rent180": 3.45,
    "rent360": 6.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinámica Ahorro",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.77,
    "rent90": 1.9,
    "rent180": 2.71,
    "rent360": 4.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Acciones Chilenas",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.84,
    "rent90": 0.74,
    "rent180": 16.09,
    "rent360": 36.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Top Picks",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 4.78,
    "rent90": 2.21,
    "rent180": 19.5,
    "rent360": 41.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Acciones Globales",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -7.99,
    "rent90": -5.43,
    "rent180": -1.09,
    "rent360": 35.26,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Asia",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.69,
    "rent90": 2.99,
    "rent180": 0.35,
    "rent360": 26.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Emergente Global",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -5.61,
    "rent90": 3.82,
    "rent180": 2.09,
    "rent360": 24.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI USA",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.85,
    "rent90": -6.86,
    "rent180": -3.43,
    "rent360": 22.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Europa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.31,
    "rent90": 0.3,
    "rent180": 0.62,
    "rent360": 19.13,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Global Titan",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.32,
    "rent90": -5.48,
    "rent180": -6.3,
    "rent360": 18.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach Arriesgado",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.25,
    "rent90": -1.5,
    "rent180": -2.37,
    "rent360": 17.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estados Unidos",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.54,
    "rent90": -6.03,
    "rent180": -8.71,
    "rent360": 16.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Acciones Sostenibles ESG",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.8,
    "rent90": -4.06,
    "rent180": -6.94,
    "rent360": 7.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Mp Liquidez",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent90": 1.07,
    "rent180": 2.17,
    "rent360": 4.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Liquidez Pesos",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.25,
    "rent90": 0.85,
    "rent180": 1.72,
    "rent360": 3.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Liquidez Pesos",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.24,
    "rent90": 0.82,
    "rent180": 1.66,
    "rent360": 3.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Liquidez Dólar",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.24,
    "rent90": 0.81,
    "rent180": 1.63,
    "rent360": 3.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Más Largo Plazo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.99,
    "rent90": 2.38,
    "rent180": 3.99,
    "rent360": 6.74,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Largo Plazo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.92,
    "rent90": 2.43,
    "rent180": 3.66,
    "rent360": 6.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta UF",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.01,
    "rent90": 2.37,
    "rent180": 3.28,
    "rent360": 5.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Pesos",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.22,
    "rent90": 1.17,
    "rent180": 2.66,
    "rent360": 5.54,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Renta UF",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.96,
    "rent90": 2.21,
    "rent180": 2.98,
    "rent360": 4.99,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Corto Plazo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.62,
    "rent90": 1.5,
    "rent180": 2.52,
    "rent360": 4.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Temático Global",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -4.38,
    "rent90": -7.56,
    "rent180": -14.64,
    "rent360": 4.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Estructurado UF Viii",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.58,
    "rent90": 2.2,
    "rent180": 2.46,
    "rent360": 4.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Tesoreria",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.31,
    "rent90": 1.05,
    "rent180": 2.12,
    "rent360": 4.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Estructurado Dólar Ii",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.08,
    "rent90": 0.8,
    "rent180": 1.11,
    "rent360": 3.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Global Dólar",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.97,
    "rent90": -1.17,
    "rent180": -0.57,
    "rent360": 3.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Estructurado UF Vii",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.64,
    "rent90": 1.26,
    "rent180": 1.58,
    "rent360": 3.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Global",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.32,
    "rent90": 1.53,
    "rent180": -3.82,
    "rent360": -1.58,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Balanceado",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.8,
    "rent90": 0.79,
    "rent180": 1.01,
    "rent360": 14.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Balanceado",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.87,
    "rent90": 0.59,
    "rent180": 0.61,
    "rent360": 13.77,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Conservador",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.56,
    "rent90": 2.15,
    "rent180": 2.5,
    "rent360": 7.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Conservador",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.55,
    "rent90": 2.15,
    "rent180": 2.47,
    "rent360": 7.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Acciones Chile Activo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.39,
    "rent90": 1.55,
    "rent180": 15.52,
    "rent360": 41.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Chile Activo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.21,
    "rent90": 1.17,
    "rent180": 14.11,
    "rent360": 35.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Chile Selectivo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.1,
    "rent90": 0.47,
    "rent180": 15.58,
    "rent360": 34.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Chile Mid Cap",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -1.72,
    "rent90": -1.31,
    "rent180": 10.45,
    "rent360": 30.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Latam",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -6.11,
    "rent90": 9.18,
    "rent180": 9.43,
    "rent360": 40.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Mercados Emergentes",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -8.03,
    "rent90": 4.92,
    "rent180": 2.56,
    "rent360": 22.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Europa",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.52,
    "rent90": 2.68,
    "rent180": 4.09,
    "rent360": 22.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Agresivo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.18,
    "rent90": -0.33,
    "rent180": -0.72,
    "rent360": 18.07,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Acciones Mundo Sustentable",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.53,
    "rent90": -2.96,
    "rent180": -5.73,
    "rent360": 17.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Mundo Sustentable",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.61,
    "rent90": -3.15,
    "rent180": -6.19,
    "rent360": 16.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Agresivo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.31,
    "rent90": -0.69,
    "rent180": -1.47,
    "rent360": 16.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Norteamerica",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -6.13,
    "rent90": -8.92,
    "rent180": -10.86,
    "rent360": 7.22,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Bonos Latam",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.99,
    "rent90": -0.72,
    "rent180": -0.04,
    "rent360": 5.1,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Very Conservative Streep",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent90": 1.02,
    "rent180": 2.02,
    "rent360": 4.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Conservative Clooney",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.12,
    "rent90": 0.42,
    "rent180": 1.15,
    "rent360": 8.52,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Moderate Pitt",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.62,
    "rent90": -2.08,
    "rent180": -1.8,
    "rent360": 17.53,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Risky Norris",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.03,
    "rent90": -2.59,
    "rent180": -2.4,
    "rent360": 33.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Corto Plazo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.67,
    "rent90": 1.65,
    "rent180": 2.85,
    "rent360": 5.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro UF",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 1.37,
    "rent90": 2.34,
    "rent180": 3.15,
    "rent360": 5.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.65,
    "rent90": 1.49,
    "rent180": 2.62,
    "rent360": 5.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Plus Dólar",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.6,
    "rent90": 1.35,
    "rent180": 2.36,
    "rent360": 4.69,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cash Dollar",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.24,
    "rent90": 0.81,
    "rent180": 1.69,
    "rent360": 3.4,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Toesca Chile Equities",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 2.12,
    "rent90": -0.29,
    "rent180": 13.42,
    "rent360": 40.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú ESG Nordea Emerging Stars",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -5.49,
    "rent90": 3.09,
    "rent180": -0.77,
    "rent360": 19.74,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Us Advantage",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.2,
    "rent90": -16.83,
    "rent180": -18.31,
    "rent360": 14.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Crecimiento Defensivo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.02,
    "rent90": -0.79,
    "rent180": -0.36,
    "rent360": 6.75,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Deuda Nominal",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.06,
    "rent90": 1.26,
    "rent180": 3.27,
    "rent360": 6.2,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú UF Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.12,
    "rent90": 2.58,
    "rent180": 3.91,
    "rent360": 6.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Deuda Corporativa Chile",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.75,
    "rent90": 2.37,
    "rent180": 3.82,
    "rent360": 6.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Income",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.6,
    "rent90": -1,
    "rent180": 1.25,
    "rent360": 5.48,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Reserva",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.72,
    "rent90": 1.58,
    "rent180": 2.62,
    "rent360": 5.15,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Select",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.36,
    "rent90": 1.18,
    "rent180": 2.39,
    "rent360": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Performance",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.27,
    "rent90": 1.13,
    "rent180": 2.36,
    "rent360": 4.89,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Select Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.26,
    "rent90": 0.89,
    "rent180": 1.82,
    "rent360": 3.75,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Latam Corporate",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.42,
    "rent90": -1.32,
    "rent180": -1.68,
    "rent360": 2.82,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú ESG Global Credits",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.1,
    "rent90": -0.66,
    "rent180": 0.14,
    "rent360": 2.64,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Global Brands",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -3.35,
    "rent90": -10.71,
    "rent180": -17.71,
    "rent360": -17.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Moderado",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1,
    "rent90": 0.13,
    "rent180": 0.66,
    "rent360": 10.4,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Crecimiento Balanceado",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -3.11,
    "rent90": -1.67,
    "rent180": -2.04,
    "rent360": 8.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Dinámico Ultra",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.84,
    "rent90": 3.56,
    "rent180": 3.72,
    "rent360": 7.57,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Dinamico Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.55,
    "rent90": 3.24,
    "rent180": 4.1,
    "rent360": 6.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Conservador",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.19,
    "rent90": 1.21,
    "rent180": 1.94,
    "rent360": 6.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Dinamico",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.9,
    "rent90": 2.12,
    "rent180": 3.19,
    "rent360": 5.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Renta Dinamica Global",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.13,
    "rent90": -0.44,
    "rent180": 1.7,
    "rent360": 5.3,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "ETF IT Now S&P IPSA",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.02,
    "rent90": 0.61,
    "rent180": 16.04,
    "rent360": 36.34,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Acciones Latinoamericanas",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.4,
    "rent90": 14.27,
    "rent180": 22.22,
    "rent360": 56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Brasil Activo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -0.34,
    "rent90": 18.51,
    "rent180": 16.44,
    "rent360": 46.78,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú National Equity",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.89,
    "rent90": -0.63,
    "rent180": 14.58,
    "rent360": 36.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Acciones Emergentes",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.05,
    "rent90": 2.27,
    "rent180": 2.05,
    "rent360": 31.19,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Top USA",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.84,
    "rent90": -3.24,
    "rent180": -4.75,
    "rent360": 22.29,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Agresivo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.07,
    "rent90": -0.64,
    "rent180": -0.42,
    "rent360": 14.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Acciones",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.37,
    "rent90": -2.91,
    "rent180": -4.92,
    "rent360": 11.73,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Crecimiento Agresivo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.33,
    "rent90": -2.77,
    "rent180": -3.98,
    "rent360": 11.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Moneda Credito Latam",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.1,
    "rent90": -0.51,
    "rent180": 0.33,
    "rent360": 5.44,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Corporativo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.91,
    "rent90": 2.16,
    "rent180": 3.25,
    "rent360": 5.57,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Capital",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 1.04,
    "rent90": 2.11,
    "rent180": 2.87,
    "rent360": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Estrategico",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.85,
    "rent90": 2,
    "rent180": 3.27,
    "rent360": 4.62,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Activo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.67,
    "rent90": 1.65,
    "rent180": 2.23,
    "rent360": 4.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro UF",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 1.24,
    "rent90": 1.95,
    "rent180": 2.21,
    "rent360": 4.03,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": -0.68,
    "rent90": -0.25,
    "rent180": 0.5,
    "rent360": 4.01,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro A Plazo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.65,
    "rent90": 1.31,
    "rent180": 1.9,
    "rent360": 3.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Money Market",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.21,
    "rent90": 0.73,
    "rent180": 1.49,
    "rent360": 2.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Latinoamericano",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -7.51,
    "rent90": 10.02,
    "rent180": 15.96,
    "rent360": 39.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Portfolio Lider",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.93,
    "rent90": 4.23,
    "rent180": 5.79,
    "rent360": 15.73,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Moderada Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.93,
    "rent90": -0.29,
    "rent180": 1.64,
    "rent360": 14.93,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Moderada",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.48,
    "rent90": 1.12,
    "rent180": 2.1,
    "rent360": 14.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Proteccion",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.42,
    "rent90": 2.04,
    "rent180": 2.83,
    "rent360": 8.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Defensiva Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.6,
    "rent90": -0.71,
    "rent180": 0.31,
    "rent360": 4.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Monetario",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.28,
    "rent90": 0.94,
    "rent180": 1.91,
    "rent360": 3.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Crecimiento",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.93,
    "rent90": 0.47,
    "rent180": 0.11,
    "rent360": 12.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Balanceado",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -1.02,
    "rent90": 0.83,
    "rent180": 1.06,
    "rent360": 9.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Conservadora Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -2.28,
    "rent90": -1.03,
    "rent180": 0.13,
    "rent360": 8.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Conservadora",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.23,
    "rent90": 1.38,
    "rent180": 2.21,
    "rent360": 8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Moderado",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": -0.22,
    "rent90": 1.32,
    "rent180": 2,
    "rent360": 7.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Conservador",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.74,
    "rent90": 1.92,
    "rent180": 2.65,
    "rent360": 5.32,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Ahorro Dinámico",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.9,
    "rent90": 2.08,
    "rent180": 3.09,
    "rent360": 5.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Acciones Nacionales",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 0.77,
    "rent90": -0.07,
    "rent180": 12.48,
    "rent360": 33.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Enfoque",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.35,
    "rent90": 1.11,
    "rent180": 17.76,
    "rent360": 44.69,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Agresiva Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.44,
    "rent90": 0.81,
    "rent180": 4.08,
    "rent360": 26.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Estados Unidos",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.84,
    "rent90": -6.6,
    "rent180": -4.63,
    "rent360": 25.44,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Asia",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -10.18,
    "rent90": -2.13,
    "rent180": -0.84,
    "rent360": 24.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Agresiva",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.55,
    "rent90": 0.75,
    "rent180": 1.35,
    "rent360": 21.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Agresivo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.54,
    "rent90": -0.18,
    "rent180": -1.13,
    "rent360": 16.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Bonos Latam",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.41,
    "rent90": -0.55,
    "rent180": 0.01,
    "rent360": 5.39,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Europa",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -8.85,
    "rent90": -9.65,
    "rent180": -6.31,
    "rent360": 3.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Ahorro Mediano Plazo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 1.29,
    "rent90": 2.07,
    "rent180": 2.45,
    "rent360": 4.42,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Money Market",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.3,
    "rent90": 1.01,
    "rent180": 2.07,
    "rent360": 4.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Money Market Dolar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.23,
    "rent90": 0.78,
    "rent180": 1.59,
    "rent360": 3.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Estructurado Ahorro+ V",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.14,
    "rent90": 0.72,
    "rent180": 1.64,
    "rent360": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Equilibrio Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -3.84,
    "rent90": -2.28,
    "rent180": 0.39,
    "rent360": 14.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Private Banking Equilibrio",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.89,
    "rent90": 0.3,
    "rent180": 1.42,
    "rent360": 10.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Gestión Activa Equilibrio",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.77,
    "rent90": 0.81,
    "rent180": 1.87,
    "rent360": 10.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Prudente Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.98,
    "rent90": -0.82,
    "rent180": 1.22,
    "rent360": 8.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Private Banking Prudente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.75,
    "rent90": 2.11,
    "rent180": 3.3,
    "rent360": 7.64,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Extra Largo Plazo UF",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.32,
    "rent90": 2.6,
    "rent180": 4.33,
    "rent360": 7.33,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Gestión Activa Prudente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.71,
    "rent90": 1.97,
    "rent180": 2.96,
    "rent360": 6.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Largo Plazo UF",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.26,
    "rent90": 2.64,
    "rent180": 3.69,
    "rent360": 6.41,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Objetivo Abril 2028",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.33,
    "rent90": 2.66,
    "rent180": 3.5,
    "rent360": 6.01,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Selecta Chile",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.11,
    "rent90": 2.42,
    "rent180": 3.41,
    "rent360": 5.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Largo Plazo Pesos",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.39,
    "rent90": 1.14,
    "rent180": 2.89,
    "rent360": 5.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Mediano Plazo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.75,
    "rent90": 1.66,
    "rent180": 2.58,
    "rent360": 5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Latam",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.2,
    "rent90": -1.31,
    "rent180": -0.71,
    "rent360": 4.68,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Tesoreria",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.29,
    "rent90": 0.98,
    "rent180": 2.01,
    "rent360": 4.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Soberana",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.45,
    "rent90": 1.67,
    "rent180": 4.79,
    "rent360": 3.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Corto Plazo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.21,
    "rent90": 0.86,
    "rent180": 1.81,
    "rent360": 3.81,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Corto Plazo Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.33,
    "rent90": 0.9,
    "rent180": 1.71,
    "rent360": 3.44,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Selectas Chile",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 4.01,
    "rent90": 2.52,
    "rent180": 18.62,
    "rent360": 43.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Chilenas",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.31,
    "rent90": 0.57,
    "rent180": 16.07,
    "rent360": 37.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Bonos Nacionales",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 1.2,
    "rent90": 2.62,
    "rent180": 3.99,
    "rent360": 6.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander GO Acciones Selectas USA",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -5.16,
    "rent90": -15.99,
    "rent180": -21.85,
    "rent360": 2.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Latinoamérica",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.41,
    "rent90": 12.58,
    "rent180": 14.66,
    "rent360": 36.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander GO Acciones Asia Emergente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -10.14,
    "rent90": 5.22,
    "rent180": 0.97,
    "rent360": 26.65,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Global Emergente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -5.18,
    "rent90": 5.08,
    "rent180": 3.39,
    "rent360": 25.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Agresivo Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -6.83,
    "rent90": -5.67,
    "rent180": -1.19,
    "rent360": 21.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Gestión Activa Agresiva",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.75,
    "rent90": 0.01,
    "rent180": 0.7,
    "rent360": 19.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Private Banking Agresivo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -1.81,
    "rent90": -0.79,
    "rent180": 0.15,
    "rent360": 19.33,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Estados Unidos",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -5.43,
    "rent90": -6.21,
    "rent180": -6.02,
    "rent360": 16.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Europa",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -5.36,
    "rent90": -2.51,
    "rent180": -2.47,
    "rent360": 10.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander GO Acciones Globales ESG",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -6.82,
    "rent90": -6.69,
    "rent180": -7.41,
    "rent360": 5.88,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Liquidez",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.26,
    "rent90": 0.86,
    "rent180": 1.73,
    "rent360": 3.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Largo Plazo UF",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1,
    "rent90": 2.29,
    "rent180": 3.31,
    "rent360": 5.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Chile Flexible",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.78,
    "rent90": 2.02,
    "rent180": 3.03,
    "rent360": 5.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Mediano Plazo UF",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.13,
    "rent90": 2.28,
    "rent180": 3.02,
    "rent360": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Corto Plazo UF",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.42,
    "rent90": 2.18,
    "rent180": 2.58,
    "rent360": 4.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Mediano Plazo",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.18,
    "rent90": 1.09,
    "rent180": 2.35,
    "rent360": 4.15,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Estructurado Deuda UF Ii",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent90": 1.23,
    "rent180": 1.59,
    "rent360": 3.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Latam Dolar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.72,
    "rent90": -1.19,
    "rent180": -0.64,
    "rent360": 3.48,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Retail Dólar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.24,
    "rent90": 0.82,
    "rent180": 1.66,
    "rent360": 3.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Global Dólar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.2,
    "rent90": -0.55,
    "rent180": 0.09,
    "rent360": 2.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Real Estate Global",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -4.94,
    "rent90": 0.71,
    "rent180": -5.9,
    "rent360": 1.5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Moderado",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.79,
    "rent90": 2.19,
    "rent180": 2.83,
    "rent360": 7.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Conservador",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.83,
    "rent90": 1.98,
    "rent180": 2.98,
    "rent360": 6.34,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Mas Conservador",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.66,
    "rent90": 1.4,
    "rent180": 2.12,
    "rent360": 4.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Acciones Chile",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.6,
    "rent90": 0.64,
    "rent180": 15.69,
    "rent360": 34.66,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Acciones Chile Mid Cap",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": -1.25,
    "rent90": 0.47,
    "rent180": 11.1,
    "rent360": 30.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Latam",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 4.35,
    "rent90": 15.56,
    "rent180": 15.54,
    "rent360": 40.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Mas Arriesgado",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -0.26,
    "rent90": 1.74,
    "rent180": 1.27,
    "rent360": 19.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Acciones USA",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -3.13,
    "rent90": -7.17,
    "rent180": -10.25,
    "rent360": 17.1,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Arriesgado",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.36,
    "rent90": 2.05,
    "rent180": 2.23,
    "rent360": 13.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Global Dolar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.09,
    "rent90": -10.99,
    "rent180": -9.35,
    "rent360": 5.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Europa",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -0.61,
    "rent90": -5.57,
    "rent180": -7.36,
    "rent360": 3.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Global",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -2.38,
    "rent90": -8.28,
    "rent180": -11.95,
    "rent360": 0.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Dolar Money Market",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.23,
    "rent90": 0.77,
    "rent180": 1.48,
    "rent360": 2.89,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Emerging Market",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -6.13,
    "rent90": 1.52,
    "rent180": 5.99,
    "rent360": 33.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Jugado",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.24,
    "rent90": -1.95,
    "rent180": 0.87,
    "rent360": 23.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Global",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -6.05,
    "rent90": -5.88,
    "rent180": -2.25,
    "rent360": 19.38,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2055",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -0.25,
    "rent90": 0.17,
    "rent180": 0.77,
    "rent360": 17.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2045",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.22,
    "rent90": 0.8,
    "rent180": 1.89,
    "rent360": 13.41,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2035",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.02,
    "rent90": 2.18,
    "rent180": 3.04,
    "rent360": 9.35,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Corporativo",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.08,
    "rent90": 2.41,
    "rent180": 3.75,
    "rent360": 6.53,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Gold",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.24,
    "rent90": 2.47,
    "rent180": 3.37,
    "rent360": 5.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Deuda Corporativa Latinoamericana",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -2.04,
    "rent90": -0.71,
    "rent180": 0.03,
    "rent360": 5.62,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2025",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0,
    "rent90": -0.02,
    "rent180": 0.62,
    "rent360": 5.58,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security First",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.06,
    "rent90": 1.34,
    "rent180": 2.81,
    "rent360": 5.37,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Mid Term UF",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.42,
    "rent90": 2.2,
    "rent180": 2.64,
    "rent360": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Defensivo",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.94,
    "rent90": 1.91,
    "rent180": 2.74,
    "rent360": 4.9,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Deuda Internacional",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": -1.82,
    "rent90": -1.05,
    "rent180": -0.04,
    "rent360": 4.5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Mid Term",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.66,
    "rent90": 1.39,
    "rent180": 2.22,
    "rent360": 4.39,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Mid Term Global",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent90": 1.14,
    "rent180": 1.92,
    "rent360": 4.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Plus",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.28,
    "rent90": 0.96,
    "rent180": 1.93,
    "rent360": 3.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Balanceado Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.35,
    "rent90": 0.99,
    "rent180": 2.26,
    "rent360": 12.9,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Digital Balanceado",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.41,
    "rent90": 1.17,
    "rent180": 2.48,
    "rent360": 12.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Digital Conservador",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.09,
    "rent90": 2.39,
    "rent180": 2.76,
    "rent360": 8.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Conservador Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.06,
    "rent90": 2.29,
    "rent180": 3.14,
    "rent360": 8.5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Index Fund S&p/clx IPSA",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.98,
    "rent90": 0.44,
    "rent180": 15.63,
    "rent360": 35.19,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Latam",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.53,
    "rent90": 14.5,
    "rent180": 24.28,
    "rent360": 60.35,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Asia Emergente",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -6.87,
    "rent90": 0.14,
    "rent180": 4.33,
    "rent360": 32.31,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Acciones EEUU",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -4.73,
    "rent90": -7,
    "rent180": -2.47,
    "rent360": 31.37,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Agresivo Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -0.27,
    "rent90": 0.09,
    "rent180": 0.88,
    "rent360": 21.26,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Europa Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -5.3,
    "rent90": -3.58,
    "rent180": 1.95,
    "rent360": 21.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Digital Agresivo",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": -0.19,
    "rent90": 0.37,
    "rent180": 2.06,
    "rent360": 18.4,
    "fee": 0,
    "desc": ""
  }
];

const DEPOSITS_DATA = {
  "BCI":[{"plazo":30,"tasa":0.32,"tasaAnual":3.90,"minMonto":500000},{"plazo":90,"tasa":0.98,"tasaAnual":4.00,"minMonto":500000},{"plazo":180,"tasa":2.05,"tasaAnual":4.15,"minMonto":1000000},{"plazo":360,"tasa":4.25,"tasaAnual":4.25,"minMonto":1000000}],
  "Banchile":[{"plazo":30,"tasa":0.31,"tasaAnual":3.80,"minMonto":500000},{"plazo":90,"tasa":0.96,"tasaAnual":3.90,"minMonto":500000},{"plazo":180,"tasa":2.00,"tasaAnual":4.05,"minMonto":1000000},{"plazo":360,"tasa":4.18,"tasaAnual":4.18,"minMonto":1000000}],
  "BancoEstado":[{"plazo":30,"tasa":0.33,"tasaAnual":4.05,"minMonto":250000},{"plazo":90,"tasa":1.02,"tasaAnual":4.15,"minMonto":250000},{"plazo":180,"tasa":2.12,"tasaAnual":4.30,"minMonto":500000},{"plazo":360,"tasa":4.40,"tasaAnual":4.40,"minMonto":500000}],
  "Scotiabank":[{"plazo":30,"tasa":0.30,"tasaAnual":3.70,"minMonto":500000},{"plazo":90,"tasa":0.93,"tasaAnual":3.80,"minMonto":500000},{"plazo":180,"tasa":1.95,"tasaAnual":3.95,"minMonto":1000000},{"plazo":360,"tasa":4.05,"tasaAnual":4.05,"minMonto":1000000}],
  "Santander":[{"plazo":30,"tasa":0.31,"tasaAnual":3.85,"minMonto":500000},{"plazo":90,"tasa":0.97,"tasaAnual":3.95,"minMonto":500000},{"plazo":180,"tasa":2.02,"tasaAnual":4.10,"minMonto":1000000},{"plazo":360,"tasa":4.20,"tasaAnual":4.20,"minMonto":1000000}],
  "Itaú":[{"plazo":30,"tasa":0.32,"tasaAnual":3.92,"minMonto":500000},{"plazo":90,"tasa":0.99,"tasaAnual":4.02,"minMonto":500000},{"plazo":180,"tasa":2.06,"tasaAnual":4.18,"minMonto":1000000},{"plazo":360,"tasa":4.28,"tasaAnual":4.28,"minMonto":1000000}],
  "Security":[{"plazo":30,"tasa":0.30,"tasaAnual":3.72,"minMonto":500000},{"plazo":90,"tasa":0.94,"tasaAnual":3.82,"minMonto":500000},{"plazo":180,"tasa":1.96,"tasaAnual":3.98,"minMonto":1000000},{"plazo":360,"tasa":4.10,"tasaAnual":4.10,"minMonto":1000000}],
  "BICE":[{"plazo":30,"tasa":0.31,"tasaAnual":3.82,"minMonto":500000},{"plazo":90,"tasa":0.96,"tasaAnual":3.88,"minMonto":500000},{"plazo":180,"tasa":1.98,"tasaAnual":4.02,"minMonto":1000000},{"plazo":360,"tasa":4.15,"tasaAnual":4.15,"minMonto":1000000}]
};

const BANK_INFO = {
  "BCI":{"url":"https://www.bci.cl/inversiones","digital":true,"minInvest":"$1.000","desc":"Banco grande con amplia oferta de fondos y plataforma digital."},
  "Banchile":{"url":"https://sitiospublicos.bancochile.cl/banchileinversiones/fondos-mutuos","digital":true,"minInvest":"$1.000","desc":"Administradora del Banco de Chile. Mayor patrimonio administrado del país."},
  "BancoEstado":{"url":"https://www.bancoestado.cl/fondosmutuos","digital":true,"minInvest":"$5.000","desc":"El banco estatal. Montos mínimos bajos y cobertura nacional."},
  "Scotiabank":{"url":"https://www.scotiabankchile.cl/Inversiones/fondos-mutuos","digital":true,"minInvest":"$10.000","desc":"Banco internacional con presencia en Chile."},
  "Santander":{"url":"https://www.santander.cl/personas/inversiones/fondos-mutuos","digital":true,"minInvest":"$5.000","desc":"Banco global con amplia gama de fondos."},
  "Itaú":{"url":"https://www.itau.cl/inversiones","digital":true,"minInvest":"$10.000","desc":"Banco brasileño con operaciones en Chile. Buena oferta digital."},
  "Fintual":{"url":"https://fintual.cl","digital":true,"minInvest":"$1","desc":"100% digital, sin mínimos. Comisión única de 1.19%. La opción fintech."},
  "Security":{"url":"https://www.inversionessecurity.cl/","digital":true,"minInvest":"$10.000","desc":"Grupo financiero chileno con fondos para distintos perfiles."},
  "BICE":{"url":"https://banco.bice.cl/inversiones/fondos-mutuos","digital":true,"minInvest":"$1","desc":"Grupo BICE. Sin monto mínimo en series digitales. 100% online."},
  "LarrainVial":{"url":"https://www.larrainvial.com","digital":true,"minInvest":"$100.000","desc":"La corredora más grande de Chile. Fondos premium."}
};

const DATA_DATE = "2026-03-28";
