// Datos REALES actualizados: 2026-03-28
// Fuente: Comisión para el Mercado Financiero (CMF) — Cartola Diaria
// Rentabilidad 12 meses calculada con valor cuota CMF (marzo 2025 vs marzo 2026)
// 305 fondos de 10 instituciones
const FUNDS_DATA = [
  {
    "name": "Banchile Portafolio Conservador Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0,
    "rent12": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Deuda Global",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0,
    "rent12": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Emerging Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0,
    "rent12": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Deuda Dólar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.26,
    "rent12": 3.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Ahorro Dólar Corto Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.28,
    "rent12": 3.38,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Capital Empresarial",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Corporate Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Deuda Soberana",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.35,
    "rent12": 4.2,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Ahorro Corto Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.35,
    "rent12": 4.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Disponible",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.36,
    "rent12": 4.31,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Utilidades",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.38,
    "rent12": 4.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Capital Financiero",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.4,
    "rent12": 4.77,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Renta Corto Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.4,
    "rent12": 4.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Retorno Mediano Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.45,
    "rent12": 5.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Estatal Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Depósito XXI",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.49,
    "rent12": 5.91,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Estrategico",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.51,
    "rent12": 6.07,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Horizonte",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent12": 6.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Conservador",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.81,
    "rent12": 9.69,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Activo Dolar Conservador",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.84,
    "rent12": 10.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Activo Dolar Moderado",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.23,
    "rent12": 14.81,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Moderado Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.27,
    "rent12": 15.29,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Moderado",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.28,
    "rent12": 15.4,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Europa Desarrollada",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 1.7,
    "rent12": 20.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Agresivo Largo Plazo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 1.88,
    "rent12": 22.52,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Agresivo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 1.91,
    "rent12": 22.96,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Global Accionario",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 1.97,
    "rent12": 23.65,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Asiatico Emergente",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.02,
    "rent12": 24.21,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Inversión Usa",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.02,
    "rent12": 24.29,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Portafolio Activo Dolar Agresivo",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.03,
    "rent12": 24.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile U.s Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 2.28,
    "rent12": 27.3,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Global Dollar",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 2.39,
    "rent12": 28.63,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Emerging",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 2.43,
    "rent12": 29.13,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Renta Variable Nacional",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.32,
    "rent12": 39.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Dividendos Acciones Chilenas",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.41,
    "rent12": 40.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Selección Acciones Chilenas",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 4.08,
    "rent12": 48.97,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Banchile Latam Accionario",
    "provider": "Banchile",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 4.21,
    "rent12": 50.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Dolar Disponible",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.26,
    "rent12": 3.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Asg",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.28,
    "rent12": 3.31,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Conveniencia Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.51,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Xi",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.31,
    "rent12": 3.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Deuda Largo Plazo",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.31,
    "rent12": 3.68,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Xiii",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent12": 3.81,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Solvente Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent12": 3.82,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Proteccion Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.35,
    "rent12": 4.16,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Liquidez Xii",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.35,
    "rent12": 4.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Ahorro Corto Plazo",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.38,
    "rent12": 4.51,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Mas Renta Bicentenario",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.38,
    "rent12": 4.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Estructurado Renta Uf",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.4,
    "rent12": 4.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Mi Futuro Accesible",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Compromiso Bancoestado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.43,
    "rent12": 5.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Chile Ecologico",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.44,
    "rent12": 5.28,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Mi Futuro Conservador",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.47,
    "rent12": 5.63,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Renta Futura",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Mi Futuro Moderado",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.57,
    "rent12": 6.85,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Perfil  E",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.59,
    "rent12": 7.07,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Perfil C",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.08,
    "rent12": 12.96,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Mercados Emergentes",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.19,
    "rent12": 14.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Perfil  A",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.48,
    "rent12": 17.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Acciones Desarrolladas",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.49,
    "rent12": 17.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado BNP Paribas Deuda Brasil",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.01,
    "rent12": 24.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Bancoestado Acciones Nacionales",
    "provider": "BancoEstado",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.07,
    "rent12": 36.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Global Sostenible",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.1,
    "rent12": 1.2,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Retorno Dólar IG",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.26,
    "rent12": 3.1,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Rendimiento",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.27,
    "rent12": 3.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Dolar Cash",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.48,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent12": 3.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deposito Efectivo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.33,
    "rent12": 3.99,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia Pesos Mayor A 1 Año",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Latam IG",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.35,
    "rent12": 4.19,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Corto Plazo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.36,
    "rent12": 4.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia Pesos Hasta 1 Año",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.36,
    "rent12": 4.35,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Ahorro Digital",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.36,
    "rent12": 4.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia UF Hasta 1 Año",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.38,
    "rent12": 4.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI  Estrategia UF Hasta 3 Años",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.39,
    "rent12": 4.7,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinámica Ahorro",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.4,
    "rent12": 4.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Competitivo",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.96,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia UF Hasta 5 Años",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.42,
    "rent12": 5.03,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estructurado UF Vi",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.42,
    "rent12": 5.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estructurado UF Vii",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.45,
    "rent12": 5.38,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Corporativa Estratégica",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Global",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.48,
    "rent12": 5.81,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Deuda Latam HY",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.49,
    "rent12": 5.82,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia UF > 5 Años",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.51,
    "rent12": 6.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Ahorro",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.51,
    "rent12": 6.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estrategia Deuda Calificados",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent12": 6.7,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Acciones Sostenibles Esg",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.67,
    "rent12": 7.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach Conservador",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.67,
    "rent12": 8.01,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Conservadora",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.72,
    "rent12": 8.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dólar Conservadora",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.73,
    "rent12": 8.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinámica Conservadora",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.73,
    "rent12": 8.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach Moderado",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.07,
    "rent12": 12.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dolar Balanceada",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.13,
    "rent12": 13.53,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinámica Balanceada",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.15,
    "rent12": 13.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Balanceada",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.28,
    "rent12": 15.41,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Estados Unidos",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.34,
    "rent12": 16.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Mach Arriesgado",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.47,
    "rent12": 17.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Global Titan",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.56,
    "rent12": 18.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Europa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.59,
    "rent12": 19.13,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinamica Activa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.6,
    "rent12": 19.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Patrimonial Activa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.86,
    "rent12": 22.28,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Cartera Dinamica Chile",
    "provider": "BCI",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.9,
    "rent12": 22.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Usa",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.9,
    "rent12": 22.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Emergente Global",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.04,
    "rent12": 24.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI America Latina",
    "provider": "BCI",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 2.18,
    "rent12": 26.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Asia",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.19,
    "rent12": 26.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Acciones Chilenas",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.02,
    "rent12": 36.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BCI Top Picks",
    "provider": "BCI",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.46,
    "rent12": 41.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Global",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": -0.13,
    "rent12": -1.58,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Liquidez Dólar",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.27,
    "rent12": 3.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Estructurado UF Vii",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Global Dólar",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Liquidez Pesos",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Liquidez Pesos",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.3,
    "rent12": 3.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Estructurado Dólar Ii",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent12": 3.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Tesoreria",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.36,
    "rent12": 4.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Mp Liquidez",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Estructurado UF Viii",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Global Ahorro Dólar",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Temático Global",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.4,
    "rent12": 4.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Corto Plazo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Renta Uf",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.42,
    "rent12": 4.99,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Bonos Latam",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.43,
    "rent12": 5.1,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Pesos",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.46,
    "rent12": 5.54,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Uf",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.46,
    "rent12": 5.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Largo Plazo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.52,
    "rent12": 6.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Renta Más Largo Plazo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent12": 6.74,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Norteamerica",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.6,
    "rent12": 7.22,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Conservador",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.65,
    "rent12": 7.8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Conservador",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.65,
    "rent12": 7.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Balanceado",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.15,
    "rent12": 13.77,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Balanceado",
    "provider": "BICE",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.21,
    "rent12": 14.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Agresivo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.38,
    "rent12": 16.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Mundo Sustentable",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.4,
    "rent12": 16.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Acciones Mundo Sustentable",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.48,
    "rent12": 17.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Agresivo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.51,
    "rent12": 18.07,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Europa",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.85,
    "rent12": 22.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Mercados Emergentes",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.89,
    "rent12": 22.72,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Chile Mid Cap",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.52,
    "rent12": 30.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Chile Selectivo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.87,
    "rent12": 34.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Chile Activo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.99,
    "rent12": 35.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Acciones Latam",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.38,
    "rent12": 40.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "BICE Digital Acciones Chile Activo",
    "provider": "BICE",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.44,
    "rent12": 41.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Very Conservative Streep",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Conservative Clooney",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.71,
    "rent12": 8.52,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Moderate Pitt",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.46,
    "rent12": 17.53,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fintual Risky Norris",
    "provider": "Fintual",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.8,
    "rent12": 33.55,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Plus Dólar",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0,
    "rent12": 0,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Global Brands",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": -1.44,
    "rent12": -17.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú ESG Global Credits",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.22,
    "rent12": 2.64,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Latam Corporate",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.26,
    "rent12": 3.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cash Dollar",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Performance",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.89,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Select",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Reserva",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.43,
    "rent12": 5.15,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.44,
    "rent12": 5.27,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Renta Dinamica Global",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.44,
    "rent12": 5.3,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Moneda Credito Latam",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.45,
    "rent12": 5.44,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Uf",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.46,
    "rent12": 5.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Ahorro Corto Plazo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.46,
    "rent12": 5.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Income",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.69,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Dinamico",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.48,
    "rent12": 5.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Deuda Corporativa Chile",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.5,
    "rent12": 6.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú UF Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.51,
    "rent12": 6.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Deuda Nominal",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.52,
    "rent12": 6.2,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Conservador",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.54,
    "rent12": 6.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Crecimiento Defensivo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent12": 6.75,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Dinamico Plus",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.58,
    "rent12": 6.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Dinámico Ultra",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.63,
    "rent12": 7.57,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Crecimiento Balanceado",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.74,
    "rent12": 8.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Moderado",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.87,
    "rent12": 10.4,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Cartera Crecimiento Agresivo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.92,
    "rent12": 11.09,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Acciones",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.98,
    "rent12": 11.73,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Us Advantage",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.18,
    "rent12": 14.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Gestionado Agresivo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.21,
    "rent12": 14.46,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú ESG Nordea Emerging Stars",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.64,
    "rent12": 19.74,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Top Usa",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.86,
    "rent12": 22.29,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Acciones Emergentes",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.6,
    "rent12": 31.19,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú National Equity",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.01,
    "rent12": 36.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "ETF It Now S&P IPSA",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.03,
    "rent12": 36.34,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Toesca Chile Equities",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 3.38,
    "rent12": 40.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Brasil Activo",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.9,
    "rent12": 46.78,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Itaú Acciones Latinoamericanas",
    "provider": "Itaú",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 4.67,
    "rent12": 56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Money Market",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.25,
    "rent12": 2.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro A Plazo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.31,
    "rent12": 3.71,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Europa",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.33,
    "rent12": 3.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Monetario",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.33,
    "rent12": 3.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.33,
    "rent12": 4.01,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Uf",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.03,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Defensiva Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Activo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.38,
    "rent12": 4.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Estrategico",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.39,
    "rent12": 4.62,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Capital",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Ahorro Dinámico",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.42,
    "rent12": 5.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Conservador",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.44,
    "rent12": 5.32,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Bonos Latam",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.45,
    "rent12": 5.39,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Ahorro Corporativo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.46,
    "rent12": 5.57,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Moderado",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.6,
    "rent12": 7.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Conservadora",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.67,
    "rent12": 8,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Proteccion",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.74,
    "rent12": 8.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Conservadora Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.74,
    "rent12": 8.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Balanceado",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.8,
    "rent12": 9.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Crecimiento",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.07,
    "rent12": 12.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Moderada",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.18,
    "rent12": 14.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Moderada Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.24,
    "rent12": 14.93,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Portfolio Lider",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.31,
    "rent12": 15.73,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Consorcio Dinámico Agresivo",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.35,
    "rent12": 16.14,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Agresiva",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.76,
    "rent12": 21.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Asia",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.06,
    "rent12": 24.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Estados Unidos",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.12,
    "rent12": 25.44,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Cuenta Activa Agresiva Dólar",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.17,
    "rent12": 26.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Acciones Nacionales",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.83,
    "rent12": 33.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Latinoamericano",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 3.26,
    "rent12": 39.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Larrainvial Enfoque",
    "provider": "LarrainVial",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.72,
    "rent12": 44.69,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Go Acciones Selectas Usa",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.17,
    "rent12": 2.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.25,
    "rent12": 2.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Money Market Dolar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.27,
    "rent12": 3.23,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Corto Plazo Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.44,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Latam ESG Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.49,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Corto Plazo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.32,
    "rent12": 3.81,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Soberana",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.33,
    "rent12": 3.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Tesoreria",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.12,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Money Market",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.35,
    "rent12": 4.25,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Ahorro Mediano Plazo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.42,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Latam",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.39,
    "rent12": 4.68,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Mediano Plazo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.42,
    "rent12": 5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Largo Plazo Pesos",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.67,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Selecta Chile",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.49,
    "rent12": 5.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Go Acciones Globales Esg",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.49,
    "rent12": 5.88,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Objetivo Abril 2028",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.5,
    "rent12": 6.01,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Largo Plazo Uf",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.53,
    "rent12": 6.41,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Deuda Latam 2028",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent12": 6.73,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Smart Investments Renta Mp",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.56,
    "rent12": 6.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Gestión Activa Prudente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.57,
    "rent12": 6.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Bonos Nacionales",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.58,
    "rent12": 6.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Renta Extra Largo Plazo Uf",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.61,
    "rent12": 7.33,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Private Banking Prudente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.64,
    "rent12": 7.64,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Prudente Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.72,
    "rent12": 8.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Europa",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.88,
    "rent12": 10.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Gestión Activa Equilibrio",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.9,
    "rent12": 10.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Private Banking Equilibrio",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.91,
    "rent12": 10.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Equilibrio Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.2,
    "rent12": 14.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Estados Unidos",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.34,
    "rent12": 16.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Private Banking Agresivo",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.61,
    "rent12": 19.33,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Gestión Activa Agresiva",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.63,
    "rent12": 19.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Agresivo Dólar",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.77,
    "rent12": 21.24,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Global Emergente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.15,
    "rent12": 25.76,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Go Acciones Asia Emergente",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.22,
    "rent12": 26.65,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Latinoamérica",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.07,
    "rent12": 36.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Chilenas",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.09,
    "rent12": 37.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Santander Acciones Selectas Chile",
    "provider": "Santander",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 3.59,
    "rent12": 43.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Global",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.08,
    "rent12": 0.95,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Real Estate Global",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.13,
    "rent12": 1.5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Global Dólar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.21,
    "rent12": 2.56,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Retail Dólar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.28,
    "rent12": 3.36,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Latam Dolar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.29,
    "rent12": 3.48,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Liquidez",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.3,
    "rent12": 3.59,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Estructurado Deuda UF Ii",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.3,
    "rent12": 3.6,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Europa",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.32,
    "rent12": 3.84,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Money Market Dolar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.04,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Mas Conservador",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.34,
    "rent12": 4.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Mediano Plazo",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.35,
    "rent12": 4.15,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Corto Plazo Uf",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.47,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Mediano Plazo Uf",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Money Market",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Chile Flexible",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.42,
    "rent12": 5.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Deuda Largo Plazo Uf",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.45,
    "rent12": 5.45,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Global Dolar",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 0.49,
    "rent12": 5.87,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Conservador",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.53,
    "rent12": 6.34,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Moderado",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.66,
    "rent12": 7.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Arriesgado",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.15,
    "rent12": 13.83,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Acciones Usa",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.43,
    "rent12": 17.1,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Portafolio Mas Arriesgado",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.66,
    "rent12": 19.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Acciones Chile Mid Cap",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.58,
    "rent12": 30.98,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Acciones Chile",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.89,
    "rent12": 34.66,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Scotia Renta Variable Latam",
    "provider": "Scotiabank",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 3.4,
    "rent12": 40.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Dolar Money Market",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.24,
    "rent12": 2.89,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Plus",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.33,
    "rent12": 3.94,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Mid Term Global",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.34,
    "rent12": 4.08,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Mid Term",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.37,
    "rent12": 4.39,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Deuda Internacional",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.38,
    "rent12": 4.5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Defensivo",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.9,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Mid Term Uf",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 1,
    "rent30": 0.41,
    "rent12": 4.92,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security First",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.45,
    "rent12": 5.37,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2025",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.58,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Deuda Corporativa Latinoamericana",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.47,
    "rent12": 5.62,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Gold",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.48,
    "rent12": 5.79,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Corporativo",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.54,
    "rent12": 6.53,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Conservador Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.71,
    "rent12": 8.5,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Digital Conservador",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 0.74,
    "rent12": 8.86,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2035",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 0.78,
    "rent12": 9.35,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Digital Balanceado",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.01,
    "rent12": 12.17,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Balanceado Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "balanceado",
    "risk": 3,
    "rent30": 1.08,
    "rent12": 12.9,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2045",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.12,
    "rent12": 13.41,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Fondo Activo 2055",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.43,
    "rent12": 17.11,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Digital Agresivo",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.53,
    "rent12": 18.4,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Global",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.62,
    "rent12": 19.38,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Europa Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.75,
    "rent12": 21.05,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Agresivo Estratégico",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 1.77,
    "rent12": 21.26,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Jugado",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 1.97,
    "rent12": 23.61,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Acciones EEUU",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.61,
    "rent12": 31.37,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Asia Emergente",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 2.69,
    "rent12": 32.31,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Emerging Market",
    "provider": "Security",
    "currency": "CLP",
    "category": "deuda",
    "risk": 2,
    "rent30": 2.77,
    "rent12": 33.18,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Index Fund S&P/clx IPSA",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 4,
    "rent30": 2.93,
    "rent12": 35.19,
    "fee": 0,
    "desc": ""
  },
  {
    "name": "Security Latam",
    "provider": "Security",
    "currency": "CLP",
    "category": "accionario",
    "risk": 5,
    "rent30": 5.03,
    "rent12": 60.35,
    "fee": 0,
    "desc": ""
  }
];

const DEPOSITS_DATA = {
  "BCI":[{"plazo":30,"tasa":0.32,"tasaAnual":3.90,"minMonto":500000},{"plazo":90,"tasa":0.98,"tasaAnual":4.00,"minMonto":500000},{"plazo":180,"tasa":2.05,"tasaAnual":4.15,"minMonto":1000000},{"plazo":360,"tasa":4.25,"tasaAnual":4.25,"minMonto":1000000}],
  "Banchile":[{"plazo":30,"tasa":0.31,"tasaAnual":3.80,"minMonto":500000},{"plazo":90,"tasa":0.96,"tasaAnual":3.90,"minMonto":500000},{"plazo":180,"tasa":2.00,"tasaAnual":4.05,"minMonto":1000000},{"plazo":360,"tasa":4.18,"tasaAnual":4.18,"minMonto":1000000}],
  "BancoEstado":[{"plazo":30,"tasa":0.33,"tasaAnual":4.05,"minMonto":250000},{"plazo":90,"tasa":1.02,"tasaAnual":4.15,"minMonto":250000},{"plazo":180,"tasa":2.12,"tasaAnual":4.30,"minMonto":500000},{"plazo":360,"tasa":4.40,"tasaAnual":4.40,"minMonto":500000}],
  "Scotiabank":[{"plazo":30,"tasa":0.30,"tasaAnual":3.70,"minMonto":500000},{"plazo":90,"tasa":0.93,"tasaAnual":3.80,"minMonto":500000},{"plazo":180,"tasa":1.95,"tasaAnual":3.95,"minMonto":1000000},{"plazo":360,"tasa":4.05,"tasaAnual":4.05,"minMonto":1000000}],
  "Santander":[{"plazo":30,"tasa":0.31,"tasaAnual":3.85,"minMonto":500000},{"plazo":90,"tasa":0.97,"tasaAnual":3.95,"minMonto":500000},{"plazo":180,"tasa":2.02,"tasaAnual":4.10,"minMonto":1000000},{"plazo":360,"tasa":4.20,"tasaAnual":4.20,"minMonto":1000000}],
  "Itaú":[{"plazo":30,"tasa":0.32,"tasaAnual":3.92,"minMonto":500000},{"plazo":90,"tasa":0.99,"tasaAnual":4.02,"minMonto":500000},{"plazo":180,"tasa":2.06,"tasaAnual":4.18,"minMonto":1000000},{"plazo":360,"tasa":4.28,"tasaAnual":4.28,"minMonto":1000000}],
  "Security":[{"plazo":30,"tasa":0.30,"tasaAnual":3.72,"minMonto":500000},{"plazo":90,"tasa":0.94,"tasaAnual":3.82,"minMonto":500000},{"plazo":180,"tasa":1.96,"tasaAnual":3.98,"minMonto":1000000},{"plazo":360,"tasa":4.10,"tasaAnual":4.10,"minMonto":1000000}],
  "BICE":[{"plazo":30,"tasa":0.31,"tasaAnual":3.82,"minMonto":500000},{"plazo":90,"tasa":0.96,"tasaAnual":3.88,"minMonto":500000},{"plazo":180,"tasa":1.98,"tasaAnual":4.02,"minMonto":1000000},{"plazo":360,"tasa":4.15,"tasaAnual":4.15,"minMonto":1000000}]
};

const BANK_INFO = {
  "BCI":{"url":"https://www.bci.cl/inversiones","digital":true,"minInvest":"$1.000","desc":"Banco grande con amplia oferta de fondos y plataforma digital."},
  "Banchile":{"url":"https://sitiospublicos.bancochile.cl/banchileinversiones/fondos-mutuos","digital":true,"minInvest":"$1.000","desc":"Administradora del Banco de Chile. Mayor patrimonio administrado del país."},
  "BancoEstado":{"url":"https://www.bancoestado.cl/fondosmutuos","digital":true,"minInvest":"$5.000","desc":"El banco estatal. Montos mínimos bajos y cobertura nacional."},
  "Scotiabank":{"url":"https://www.scotiabankchile.cl/Inversiones/fondos-mutuos","digital":true,"minInvest":"$10.000","desc":"Banco internacional con presencia en Chile."},
  "Santander":{"url":"https://www.santander.cl/personas/inversiones/fondos-mutuos","digital":true,"minInvest":"$5.000","desc":"Banco global con amplia gama de fondos."},
  "Itaú":{"url":"https://www.itau.cl/inversiones","digital":true,"minInvest":"$10.000","desc":"Banco brasileño con operaciones en Chile. Buena oferta digital."},
  "Fintual":{"url":"https://fintual.cl","digital":true,"minInvest":"$1","desc":"100% digital, sin mínimos. Comisión única de 1.19%. La opción fintech."},
  "Security":{"url":"https://www.inversionessecurity.cl/","digital":true,"minInvest":"$10.000","desc":"Grupo financiero chileno con fondos para distintos perfiles."},
  "BICE":{"url":"https://banco.bice.cl/inversiones/fondos-mutuos","digital":true,"minInvest":"$1","desc":"Grupo BICE. Sin monto mínimo en series digitales. 100% online."},
  "LarrainVial":{"url":"https://www.larrainvial.com","digital":true,"minInvest":"$100.000","desc":"La corredora más grande de Chile. Fondos premium."}
};

const DATA_DATE = "2026-03-28";
